openapi: 3.0.0
info:
  title: leaderboard-api
  version: 1.0.0
servers:
  - url: https://leaderboard-api-test.alienworlds.io/v1/leaderboard
    description: Test server
  - url: https://leaderboard-api.alienworlds.io/v1/leaderboard
    description: Production leaderboard API server
  - url: https://api.alienworlds.io/v1/leaderboard
    description: Producton API server
  - url: http://localhost:8800/v1/leaderboard
    description: Local API server

paths:
  /list:
    get:
      tags:
        - default
      summary: /list
      parameters:
        - name: date
          in: query
          schema:
            type: string
          description: >-
            (optional) Date within the defined timeframe. Based on this value,
            the start and end of the timeframe will be calculated
          example: '2023-04-27T00:00:00.000Z'
        - name: fromDate
          in: query
          schema:
            type: string
          description: (optional) Fixed timeframe start value.
          example: '2022-04-25T00:00:00.000Z'
        - name: toDate
          in: query
          schema:
            type: string
          description: (optional) Fixed timeframe end value.
          example: '2023-04-26T23:59:59.999Z'
        - name: timeframe
          in: query
          schema:
            type: string
          description: timeframe (daily / weekly / monthly)
          example: daily
        - name: sort
          in: query
          schema:
            type: string
          description: >-
            Possible values (tlm_gains_total, total_nft_points, avg_charge_time,
            avg_mining_power, avg_nft_power, lands_mined_on, planets_mined_on,
            unique_tools_used)
          example: tlm_gains_total
        - name: order
          in: query
          schema:
            type: integer
          description: Desc = -1, Asc = 1
          example: '1'
        - name: offset
          in: query
          schema:
            type: integer
          description: Number of items to skip before starting to return result set
          example: '0'
        - name: limit
          in: query
          schema:
            type: integer
          description: Number of result items to return
          example: '3'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: daily leaderboard
                  value:
                    results:
                      - wallet_id: eamom.c.wam
                        username: mkdkzD
                        tlm_gains_total: 630.9882
                        tlm_gains_highest: 7.9861
                        total_nft_points: 4480
                        total_charge_time: 34500
                        avg_charge_time: 34500
                        total_mining_power: 5750
                        avg_mining_power: 5750
                        total_nft_power: 690
                        avg_nft_power: 690
                        lands_mined_on: 6
                        planets_mined_on: 6
                        unique_tools_used: 0
                        position: 1
                      - wallet_id: eimom.c.wam
                        username: kEpQDi
                        tlm_gains_total: 593.6424
                        tlm_gains_highest: 6.9157
                        total_nft_points: 4520
                        total_charge_time: 35100
                        avg_charge_time: 35100
                        total_mining_power: 5850
                        avg_mining_power: 5850
                        total_nft_power: 702
                        avg_nft_power: 702
                        lands_mined_on: 6
                        planets_mined_on: 6
                        unique_tools_used: 0
                        position: 2
                      - wallet_id: dumom.c.wam
                        username: ktdfyp
                        tlm_gains_total: 593.2855
                        tlm_gains_highest: 7.3974
                        total_nft_points: 4560
                        total_charge_time: 33900
                        avg_charge_time: 33900
                        total_mining_power: 5650
                        avg_mining_power: 5650
                        total_nft_power: 678
                        avg_nft_power: 678
                        lands_mined_on: 6
                        planets_mined_on: 6
                        unique_tools_used: 0
                        position: 3
                    total: 234375
                example-1:
                  summary: ascending order
                  value:
                    results:
                      - wallet_id: .cs2q.c.wam
                        tlm_gains_total: 0
                        tlm_gains_highest: 0
                        total_nft_points: 88
                        total_charge_time: 0
                        avg_charge_time: 0
                        total_mining_power: 0
                        avg_mining_power: 0
                        total_nft_power: 0
                        avg_nft_power: 0
                        lands_mined_on: 0
                        planets_mined_on: 0
                        unique_tools_used: 0
                        position: 234455
                      - wallet_id: .ggr.wam
                        tlm_gains_total: 0
                        tlm_gains_highest: 0
                        total_nft_points: 532
                        total_charge_time: 0
                        avg_charge_time: 0
                        total_mining_power: 0
                        avg_mining_power: 0
                        total_nft_power: 0
                        avg_nft_power: 0
                        lands_mined_on: 0
                        planets_mined_on: 0
                        unique_tools_used: 0
                        position: 234454
                      - wallet_id: .grog.c.wam
                        tlm_gains_total: 0
                        tlm_gains_highest: 0
                        total_nft_points: 138
                        total_charge_time: 0
                        avg_charge_time: 0
                        total_mining_power: 0
                        avg_mining_power: 0
                        total_nft_power: 0
                        avg_nft_power: 0
                        lands_mined_on: 0
                        planets_mined_on: 0
                        unique_tools_used: 0
                        position: 234453
                    total: 234455
                example-2:
                  summary: by date
                  value:
                    results:
                      - wallet_id: .cs2q.c.wam
                        tlm_gains_total: 0
                        tlm_gains_highest: 0
                        total_nft_points: 88
                        total_charge_time: 0
                        avg_charge_time: 0
                        total_mining_power: 0
                        avg_mining_power: 0
                        total_nft_power: 0
                        avg_nft_power: 0
                        lands_mined_on: 0
                        planets_mined_on: 0
                        unique_tools_used: 0
                        position: 234475
                      - wallet_id: .ggr.wam
                        tlm_gains_total: 0
                        tlm_gains_highest: 0
                        total_nft_points: 532
                        total_charge_time: 0
                        avg_charge_time: 0
                        total_mining_power: 0
                        avg_mining_power: 0
                        total_nft_power: 0
                        avg_nft_power: 0
                        lands_mined_on: 0
                        planets_mined_on: 0
                        unique_tools_used: 0
                        position: 234474
                      - wallet_id: .grog.c.wam
                        tlm_gains_total: 0
                        tlm_gains_highest: 0
                        total_nft_points: 138
                        total_charge_time: 0
                        avg_charge_time: 0
                        total_mining_power: 0
                        avg_mining_power: 0
                        total_nft_power: 0
                        avg_nft_power: 0
                        lands_mined_on: 0
                        planets_mined_on: 0
                        unique_tools_used: 0
                        position: 234473
                    total: 234475
                example-3:
                  summary: fromDate - toDate
                  value:
                    results:
                      - wallet_id: nujrc.wam
                        tlm_gains_total: 0
                        tlm_gains_highest: 0
                        total_nft_points: 2970
                        total_charge_time: 0
                        avg_charge_time: 0
                        total_mining_power: 0
                        avg_mining_power: 0
                        total_nft_power: 0
                        avg_nft_power: 0
                        lands_mined_on: 0
                        planets_mined_on: 0
                        unique_tools_used: 0
                        position: -1
                      - wallet_id: v.x3q.c.wam
                        tlm_gains_total: 0
                        tlm_gains_highest: 0
                        total_nft_points: 2160
                        total_charge_time: 0
                        avg_charge_time: 0
                        total_mining_power: 0
                        avg_mining_power: 0
                        total_nft_power: 0
                        avg_nft_power: 0
                        lands_mined_on: 0
                        planets_mined_on: 0
                        unique_tools_used: 0
                        position: -1
                      - wallet_id: vttvs.wam
                        tlm_gains_total: 0
                        tlm_gains_highest: 0
                        total_nft_points: 1500
                        total_charge_time: 0
                        avg_charge_time: 0
                        total_mining_power: 0
                        avg_mining_power: 0
                        total_nft_power: 0
                        avg_nft_power: 0
                        lands_mined_on: 0
                        planets_mined_on: 0
                        unique_tools_used: 0
                        position: -1
                    total: 21150
  /find:
    get:
      tags:
        - default
      summary: /find
      parameters:
        - name: user
          in: query
          schema:
            type: string
          required: true
          description: user's wallet id
          example: uzv4m.c.wam
        - name: timeframe
          in: query
          schema:
            type: string
          description: (optional) timeframe (daily / weekly / monthly)
          example: monthly
        - name: date
          in: query
          schema:
            type: string
          description: >-
            (optional) Date within the defined timeframe. Based on this value,
            the start and end of the timeframe will be calculated
          example: '2023-04-27T00:00:00.000Z'
        - name: fromDate
          in: query
          schema:
            type: string
          description: (optional) Fixed timeframe start value.
          example: '2023-04-20T00:00:00.000Z'
        - name: toDate
          in: query
          schema:
            type: string
          description: (optional) Fixed timeframe end value.
          example: '2023-04-26T23:59:59.000Z'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: success - user found
                  value:
                    results:
                      - wallet_id: uzv4m.c.wam
                        tlm_gains_total: 297.597
                        tlm_gains_highest: 6.7293
                        total_nft_points: 2800
                        total_charge_time: 16500
                        avg_charge_time: 16500
                        total_mining_power: 2750
                        avg_mining_power: 2750
                        total_nft_power: 330
                        avg_nft_power: 330
                        lands_mined_on: 1
                        planets_mined_on: 1
                        unique_tools_used: 0
                        position: 10
                    total: 1
                example-1:
                  summary: user not found
                  value:
                    results: []
                    total: 0
                example-2:
                  summary: timeframe param
                  value:
                    results:
                      - wallet_id: uzv4m.c.wam
                        tlm_gains_total: 1176.7619
                        tlm_gains_highest: 7.7467
                        total_nft_points: 10800
                        total_charge_time: 63600
                        avg_charge_time: 63600
                        total_mining_power: 10600
                        avg_mining_power: 10600
                        total_nft_power: 1272
                        avg_nft_power: 1272
                        lands_mined_on: 1
                        planets_mined_on: 1
                        unique_tools_used: 0
                        position: 11
                    total: 1
                example-3:
                  summary: date param
                  value:
                    results:
                      - wallet_id: uzv4m.c.wam
                        tlm_gains_total: 297.597
                        tlm_gains_highest: 6.7293
                        total_nft_points: 2800
                        total_charge_time: 16500
                        avg_charge_time: 16500
                        total_mining_power: 2750
                        avg_mining_power: 2750
                        total_nft_power: 330
                        avg_nft_power: 330
                        lands_mined_on: 1
                        planets_mined_on: 1
                        unique_tools_used: 0
                        position: 10
                    total: 1
                example-4:
                  summary: fromDate - toDate
                  value:
                    results:
                      - wallet_id: uzv4m.c.wam
                        tlm_gains_total: 101.0361
                        tlm_gains_highest: 7.1121
                        total_nft_points: 950
                        total_charge_time: 5400
                        avg_charge_time: 5400
                        total_mining_power: 900
                        avg_mining_power: 900
                        total_nft_power: 108
                        avg_nft_power: 108
                        lands_mined_on: 1
                        planets_mined_on: 1
                        unique_tools_used: 0
                        position: 10
                    total: 1
  /:
    post:
      tags:
        - default
      summary: update leaderboard
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_id: foo.bar.wam
                username: FooBar
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /health:
    get:
      tags:
        - default
      summary: /health
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: healthy status response
                  value:
                    status: OK
                    version: 0.0.1
                    timestamp: 1683807457996
                    uptimeSeconds: 149
                    nodeVersion: v17.4.0
                    dependencies:
                      '@alien-worlds/api-core': ^0.0.101
                      '@alien-worlds/dao-api-common': ^0.0.82
                    databases:
                      mongo: OK
                      redis: OK
                example-1:
                  summary: unavailable database response
                  value:
                    status: OK
                    version: 0.0.1
                    timestamp: 1683807457996
                    uptimeSeconds: 149
                    nodeVersion: v17.4.0
                    dependencies:
                      '@alien-worlds/api-core': ^0.0.101
                      '@alien-worlds/dao-api-common': ^0.0.82
                    databases:
                      mongo: OK
                      redis: OK
  /docs:
    get:
      tags:
        - default
      summary: /docs
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
